export const TOGGLE_PRODUCTS = "TOGGLE_PRODUCTS";
export const LOAD_INVENTORY = "LOAD_INVENTORY";
export const CART_STATUS = "CART_STATUS";
export const MODAL_STATUS = "MODAL_STATUS";
export const QUANTITY = "QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const TOGGLE_PROFILE = "TOGGLE_PROFILE";
